blank_issues_enabled: false
contact_links:
  - name: Security Vulnerability
    url: https://github.com/entrefix/mrbrain/security/advisories/new
    about: Please report security vulnerabilities privately here

